from db.connection import run

run('CREATE TABLE IF NOT EXISTS campus ('
    'campus_id INT PRIMARY KEY AUTO_INCREMENT,'
    'campus_name VARCHAR(64) NOT NULL,'
    'address VARCHAR(64) DEFAULT NULL,'
    'UNIQUE KEY (campus_name),'
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    ') engine=InnoDB;')

run('CREATE TABLE IF NOT EXISTS building ('
    'building_id INT PRIMARY KEY AUTO_INCREMENT,'
    'campus_id INT NOT NULL,'
    'building_name VARCHAR(64) NOT NULL,'
    'building_type ENUM(\'教学楼\',\'宿舍楼\',\'办公楼\',\'实验楼\',\'体育馆\',\'食堂\',\'其他\') NOT NULL,'
    'UNIQUE KEY (building_name),'
    'FOREIGN KEY (campus_id) REFERENCES campus(campus_id) ON UPDATE CASCADE ON DELETE RESTRICT,'
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
    ') engine=InnoDB;')

run('CREATE TABLE IF NOT EXISTS facility ('
    'facility_id INT PRIMARY KEY AUTO_INCREMENT,'
    'building_id INT NOT NULL,'
    'facility_name VARCHAR(64) NOT NULL,'
    'facility_type ENUM(\'餐厅\',\'水吧\',\'自习室\',\'办公室\',\'卫生间\',\'教室\',\'寝室\',\'其他\') NOT NULL,'
    'open_time VARCHAR(128),'
    'FOREIGN KEY (building_id) REFERENCES building(building_id) ON UPDATE CASCADE ON DELETE CASCADE,'
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    ') engine=InnoDB;')

run('CREATE TABLE IF NOT EXISTS teacher ('
    'teacher_id INT PRIMARY KEY AUTO_INCREMENT,'
    'teacher_name VARCHAR(64) NOT NULL,'
    'department VARCHAR(64) DEFAULT NULL,'
    'email VARCHAR(64) NOT NULL,'
    'UNIQUE KEY (email),'
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    ') engine=InnoDB;')

run('CREATE TABLE IF NOT EXISTS course ('
    'course_id INT PRIMARY KEY AUTO_INCREMENT,'
    'course_name VARCHAR(128) NOT NULL,'
    'credit DECIMAL(3,1) DEFAULT NULL,'
    'offering_department VARCHAR(64) DEFAULT NULL,'
    'semester VARCHAR(16) NOT NULL,'
    'section_no VARCHAR(16) NOT NULL,'
    'UNIQUE KEY (course_name, offering_department, semester, section_no),'
    'CHECK (credit IS NULL OR (credit >= 0 AND credit <= 10)),'
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    ') engine=InnoDB;')

run('CREATE TABLE IF NOT EXISTS teach ('
    'teacher_id INT NOT NULL,'
    'course_id INT NOT NULL,'
    'teach_role ENUM(\'教师\', \'助教\') DEFAULT \'教师\','
    'start_time DATETIME,'
    'end_time DATETIME,'
    'PRIMARY KEY (teacher_id, course_id),'
    'CHECK (start_time IS NULL OR end_time IS NULL OR start_time <= end_time),'
    'FOREIGN KEY (teacher_id) REFERENCES teacher(teacher_id) ON UPDATE CASCADE ON DELETE CASCADE,'
    'FOREIGN KEY (course_id) REFERENCES course(course_id) ON UPDATE CASCADE ON DELETE CASCADE,'
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    ') engine=InnoDB;')

run('CREATE TABLE IF NOT EXISTS event ('
    'event_id INT PRIMARY KEY AUTO_INCREMENT,'
    'building_id INT NOT NULL,'
    'event_name VARCHAR(128) NOT NULL,'
    'start_time DATETIME DEFAULT NULL,'
    'end_time DATETIME DEFAULT NULL,'
    'organizer VARCHAR(128) DEFAULT NULL,'
    'description TEXT DEFAULT NULL,'
    'CHECK (start_time IS NULL OR end_time IS NULL OR start_time <= end_time),'
    'FOREIGN KEY (building_id) REFERENCES building(building_id) ON UPDATE CASCADE ON DELETE CASCADE,'
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    ') engine=InnoDB;')

run('CREATE TABLE IF NOT EXISTS user_account ('
    'user_id INT PRIMARY KEY AUTO_INCREMENT,'
    'username VARCHAR(32) NOT NULL,'
    'password VARCHAR(255) NOT NULL,'
    'role ENUM(\'user\',\'admin\') DEFAULT \'user\','
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    ') engine=InnoDB;')

run('CREATE TABLE IF NOT EXISTS query_record ('
    'record_id INT PRIMARY KEY AUTO_INCREMENT,'
    'user_id INT NOT NULL,'
    'query_type ENUM(\'keyword\',\'natural_language\') NOT NULL,'
    'query_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'query_text TEXT NOT NULL,'
    'answer MEDIUMTEXT,'
    'FOREIGN KEY (user_id) REFERENCES user_account(user_id) ON UPDATE CASCADE ON DELETE CASCADE,'
    'create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
    'update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    ') engine=InnoDB;')
